name: gnrllybttr_query
description: "A generally better server state manager"
version: 0.0.1
homepage: https://github.com/GnrllyBttr/GnrllyBttrFlutterPackages/tree/main/packages/gnrllybttr_query
repository: https://github.com/GnrllyBttr/GnrllyBttrFlutterPackages/tree/main/packages/gnrllybttr_query
issue_tracker: https://github.com/GnrllyBttr/GnrllyBttrFlutterPackages/issues?q=is%3Aissue+label%3Agnrllybttr_query
documentation: https://github.com/GnrllyBttr/GnrllyBttrFlutterPackages/blob/main/packages/gnrllybttr_query/README.md

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.9

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  
  import_sorter: ^4.6.0

  mocktail: ^1.0.3


flutter:
  uses-material-design: true

import_sorter:
  comments: true
  emojis: true